---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-cleaner
  namespace: das
spec:
  project: default
  source:
    repoURL: https://github.com/StatCan/namespace-cleaner.git
    path: manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: das
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
