---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-cleaner
  namespace: das
  labels:
    app: namespace-cleaner
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: namespace-cleaner
        spec:
          serviceAccountName: namespace-cleaner
          containers:
            - name: namespace-cleaner-container
              image: artifactory.cloud.statcan.ca/das-aaw-docker/namespace-cleaner:d158c5b9068f6506a7b1fc70eda22e040b314b9f
              envFrom:
                - secretRef:
                    name: microsoft-graph-api-secret
                - configMapRef:
                    name: namespace-cleaner-config
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: Never
