---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-cleaner
  namespace: das
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: namespace-cleaner
          containers:
            - name: namespace-cleaner-container
              image: artifactory.cloud.statcan.ca/das-aaw-docker/namespace-cleaner:3764f2215032ac48f73d5833b56530689e64e1d6
              envFrom:
                - secretRef:
                    name: microsoft-graph-api-secret
                - configMapRef:
                    name: namespace-cleaner-config
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: Never
