---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-cleaner
  namespace: bryan-paget
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: namespace-cleaner-container
              image: artifactory.cloud.statcan.ca/das-aaw-docker/namespace-cleaner:8a15ac897db4b50a795285dd67d29bd310845bf7
              envFrom:
                - secretRef:
                    name: azure-creds
                - configMapRef:
                    name: namespace-cleaner-config
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: Never
