---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: namespace-cleaner
  namespace: das
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: namespace-cleaner
          containers:
            - name: namespace-cleaner-container
              image: artifactory.cloud.statcan.ca/das-aaw-docker/namespace-cleaner:fa0f92224f2f233193745d4bbc9ca553f9fa4554
              envFrom:
                - secretRef:
                    name: microsoft-graph-api-secret
                - configMapRef:
                    name: namespace-cleaner-config
              resources:
                limits:
                  memory: "256Mi"
                  cpu: "500m"
          restartPolicy: Never
