---
name: CI Pipeline

on: [push, pull_request]

env:
  GO_VERSION: 1.24
  KIND_VERSION: v0.27.0
  IMAGE_NAME: namespace-cleaner:test
  REGISTRY: k8scc01covidacr.azurecr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run yamllint
        run: |
          pip install yamllint
          yamllint .

  build:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      image-tarball: namespace-cleaner.tar
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Save Docker Image to Tarball
        run: docker save -o namespace-cleaner.tar ${{ env.IMAGE_NAME }}

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tarball
          path: namespace-cleaner.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for branch detection
          ref: ${{ github.head_ref || github.ref_name }} # Handle PR branches

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install gobadge
        run: go install github.com/AlexBeauchemin/gobadge@latest

      - name: Run Unit Tests
        run: make test-unit

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          file: coverage-report/coverage.out

      - name: Commit updated README
        if: github.ref == 'refs/heads/main' # Only run on main branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -B main
          git add README.md
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: image-tarball

      - name: Load Docker Image
        run: docker load -i namespace-cleaner.tar

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/${{ env.KIND_VERSION }}/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Create Kind Cluster
        run: kind create cluster

      - name: Load Image into Kind
        run: kind load docker-image ${{ env.IMAGE_NAME }}

      - name: Run Integration Tests
        run: make test-integration

  scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: image-tarball

      - name: Load Docker Image
        run: docker load -i namespace-cleaner.tar

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}
          severity: "CRITICAL"
          ignore-unfixed: true
          exit-code: 1
          format: table

  push:
    runs-on: ubuntu-latest
    needs: [build, test, scan]
    steps:
      - uses: actions/checkout@v4

      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: image-tarball

      - name: Load Docker Image
        run: docker load -i namespace-cleaner.tar

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag and Push Image
        run: |
          docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/namespace-cleaner:${{ github.sha }}
          docker push ${{ env.REGISTRY }}/namespace-cleaner:${{ github.sha }}
